/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SelectRouteImport } from './routes/select'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperSubjectsRouteImport } from './routes/super.subjects'
import { Route as SuperSemestersRouteImport } from './routes/super.semesters'
import { Route as SuperRequestsRouteImport } from './routes/super.requests'
import { Route as SuperMaterialsRouteImport } from './routes/super.materials'
import { Route as SuperFeedbackRouteImport } from './routes/super.feedback'
import { Route as SuperDeadlinesRouteImport } from './routes/super.deadlines'
import { Route as SuperAnalyticsRouteImport } from './routes/super.analytics'
import { Route as SuperAdminsRouteImport } from './routes/super.admins'
import { Route as SuperActivityRouteImport } from './routes/super.activity'
import { Route as SubjectIdRouteImport } from './routes/subject.$id'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminMaterialsRouteImport } from './routes/admin.materials'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminDeadlinesRouteImport } from './routes/admin.deadlines'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramNotifyMaterialsRouteImport } from './routes/api/public/telegram/notify-materials'
import { Route as ApiPublicTelegramHealthRouteImport } from './routes/api/public/telegram/health'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperSubjectsRoute = SuperSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSemestersRoute = SuperSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => SuperRoute,
} as any)
const SuperRequestsRoute = SuperRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => SuperRoute,
} as any)
const SuperMaterialsRoute = SuperMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => SuperRoute,
} as any)
const SuperFeedbackRoute = SuperFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDeadlinesRoute = SuperDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAnalyticsRoute = SuperAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAdminsRoute = SuperAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperRoute,
} as any)
const SuperActivityRoute = SuperActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperRoute,
} as any)
const SubjectIdRoute = SubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeadlinesRoute = AdminDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramNotifyMaterialsRoute =
  ApiPublicTelegramNotifyMaterialsRouteImport.update({
    id: '/api/public/telegram/notify-materials',
    path: '/api/public/telegram/notify-materials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramHealthRoute = ApiPublicTelegramHealthRouteImport.update({
  id: '/api/public/telegram/health',
  path: '/api/public/telegram/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select': typeof SelectRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/deadlines': typeof AdminDeadlinesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/deadlines': typeof SuperDeadlinesRoute
  '/super/feedback': typeof SuperFeedbackRoute
  '/super/materials': typeof SuperMaterialsRoute
  '/super/requests': typeof SuperRequestsRoute
  '/super/semesters': typeof SuperSemestersRoute
  '/super/subjects': typeof SuperSubjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/notify-materials': typeof ApiPublicTelegramNotifyMaterialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select': typeof SelectRoute
  '/admin/deadlines': typeof AdminDeadlinesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/deadlines': typeof SuperDeadlinesRoute
  '/super/feedback': typeof SuperFeedbackRoute
  '/super/materials': typeof SuperMaterialsRoute
  '/super/requests': typeof SuperRequestsRoute
  '/super/semesters': typeof SuperSemestersRoute
  '/super/subjects': typeof SuperSubjectsRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/notify-materials': typeof ApiPublicTelegramNotifyMaterialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select': typeof SelectRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/deadlines': typeof AdminDeadlinesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/deadlines': typeof SuperDeadlinesRoute
  '/super/feedback': typeof SuperFeedbackRoute
  '/super/materials': typeof SuperMaterialsRoute
  '/super/requests': typeof SuperRequestsRoute
  '/super/semesters': typeof SuperSemestersRoute
  '/super/subjects': typeof SuperSubjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/notify-materials': typeof ApiPublicTelegramNotifyMaterialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/select'
    | '/super'
    | '/admin/deadlines'
    | '/admin/feedback'
    | '/admin/materials'
    | '/admin/profile'
    | '/admin/requests'
    | '/subject/$id'
    | '/super/activity'
    | '/super/admins'
    | '/super/analytics'
    | '/super/deadlines'
    | '/super/feedback'
    | '/super/materials'
    | '/super/requests'
    | '/super/semesters'
    | '/super/subjects'
    | '/admin/'
    | '/super/'
    | '/api/public/telegram/health'
    | '/api/public/telegram/notify-materials'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/select'
    | '/admin/deadlines'
    | '/admin/feedback'
    | '/admin/materials'
    | '/admin/profile'
    | '/admin/requests'
    | '/subject/$id'
    | '/super/activity'
    | '/super/admins'
    | '/super/analytics'
    | '/super/deadlines'
    | '/super/feedback'
    | '/super/materials'
    | '/super/requests'
    | '/super/semesters'
    | '/super/subjects'
    | '/admin'
    | '/super'
    | '/api/public/telegram/health'
    | '/api/public/telegram/notify-materials'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/select'
    | '/super'
    | '/admin/deadlines'
    | '/admin/feedback'
    | '/admin/materials'
    | '/admin/profile'
    | '/admin/requests'
    | '/subject/$id'
    | '/super/activity'
    | '/super/admins'
    | '/super/analytics'
    | '/super/deadlines'
    | '/super/feedback'
    | '/super/materials'
    | '/super/requests'
    | '/super/semesters'
    | '/super/subjects'
    | '/admin/'
    | '/super/'
    | '/api/public/telegram/health'
    | '/api/public/telegram/notify-materials'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  SelectRoute: typeof SelectRoute
  SuperRoute: typeof SuperRouteWithChildren
  SubjectIdRoute: typeof SubjectIdRoute
  ApiPublicTelegramHealthRoute: typeof ApiPublicTelegramHealthRoute
  ApiPublicTelegramNotifyMaterialsRoute: typeof ApiPublicTelegramNotifyMaterialsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super/subjects': {
      id: '/super/subjects'
      path: '/subjects'
      fullPath: '/super/subjects'
      preLoaderRoute: typeof SuperSubjectsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/semesters': {
      id: '/super/semesters'
      path: '/semesters'
      fullPath: '/super/semesters'
      preLoaderRoute: typeof SuperSemestersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/requests': {
      id: '/super/requests'
      path: '/requests'
      fullPath: '/super/requests'
      preLoaderRoute: typeof SuperRequestsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/materials': {
      id: '/super/materials'
      path: '/materials'
      fullPath: '/super/materials'
      preLoaderRoute: typeof SuperMaterialsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/feedback': {
      id: '/super/feedback'
      path: '/feedback'
      fullPath: '/super/feedback'
      preLoaderRoute: typeof SuperFeedbackRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/deadlines': {
      id: '/super/deadlines'
      path: '/deadlines'
      fullPath: '/super/deadlines'
      preLoaderRoute: typeof SuperDeadlinesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/analytics': {
      id: '/super/analytics'
      path: '/analytics'
      fullPath: '/super/analytics'
      preLoaderRoute: typeof SuperAnalyticsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/admins': {
      id: '/super/admins'
      path: '/admins'
      fullPath: '/super/admins'
      preLoaderRoute: typeof SuperAdminsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/activity': {
      id: '/super/activity'
      path: '/activity'
      fullPath: '/super/activity'
      preLoaderRoute: typeof SuperActivityRouteImport
      parentRoute: typeof SuperRoute
    }
    '/subject/$id': {
      id: '/subject/$id'
      path: '/subject/$id'
      fullPath: '/subject/$id'
      preLoaderRoute: typeof SubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deadlines': {
      id: '/admin/deadlines'
      path: '/deadlines'
      fullPath: '/admin/deadlines'
      preLoaderRoute: typeof AdminDeadlinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/notify-materials': {
      id: '/api/public/telegram/notify-materials'
      path: '/api/public/telegram/notify-materials'
      fullPath: '/api/public/telegram/notify-materials'
      preLoaderRoute: typeof ApiPublicTelegramNotifyMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/health': {
      id: '/api/public/telegram/health'
      path: '/api/public/telegram/health'
      fullPath: '/api/public/telegram/health'
      preLoaderRoute: typeof ApiPublicTelegramHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDeadlinesRoute: typeof AdminDeadlinesRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDeadlinesRoute: AdminDeadlinesRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperActivityRoute: typeof SuperActivityRoute
  SuperAdminsRoute: typeof SuperAdminsRoute
  SuperAnalyticsRoute: typeof SuperAnalyticsRoute
  SuperDeadlinesRoute: typeof SuperDeadlinesRoute
  SuperFeedbackRoute: typeof SuperFeedbackRoute
  SuperMaterialsRoute: typeof SuperMaterialsRoute
  SuperRequestsRoute: typeof SuperRequestsRoute
  SuperSemestersRoute: typeof SuperSemestersRoute
  SuperSubjectsRoute: typeof SuperSubjectsRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperActivityRoute: SuperActivityRoute,
  SuperAdminsRoute: SuperAdminsRoute,
  SuperAnalyticsRoute: SuperAnalyticsRoute,
  SuperDeadlinesRoute: SuperDeadlinesRoute,
  SuperFeedbackRoute: SuperFeedbackRoute,
  SuperMaterialsRoute: SuperMaterialsRoute,
  SuperRequestsRoute: SuperRequestsRoute,
  SuperSemestersRoute: SuperSemestersRoute,
  SuperSubjectsRoute: SuperSubjectsRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  SelectRoute: SelectRoute,
  SuperRoute: SuperRouteWithChildren,
  SubjectIdRoute: SubjectIdRoute,
  ApiPublicTelegramHealthRoute: ApiPublicTelegramHealthRoute,
  ApiPublicTelegramNotifyMaterialsRoute: ApiPublicTelegramNotifyMaterialsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
