/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SelectRouteImport } from './routes/select'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperSemestersRouteImport } from './routes/super.semesters'
import { Route as SuperActivityRouteImport } from './routes/super.activity'
import { Route as SubjectIdRouteImport } from './routes/subject.$id'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperSemestersRoute = SuperSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => SuperRoute,
} as any)
const SuperActivityRoute = SuperActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperRoute,
} as any)
const SubjectIdRoute = SubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select': typeof SelectRoute
  '/super': typeof SuperRouteWithChildren
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/semesters': typeof SuperSemestersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select': typeof SelectRoute
  '/super': typeof SuperRouteWithChildren
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/semesters': typeof SuperSemestersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select': typeof SelectRoute
  '/super': typeof SuperRouteWithChildren
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/semesters': typeof SuperSemestersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/select'
    | '/super'
    | '/subject/$id'
    | '/super/activity'
    | '/super/semesters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/select'
    | '/super'
    | '/subject/$id'
    | '/super/activity'
    | '/super/semesters'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/select'
    | '/super'
    | '/subject/$id'
    | '/super/activity'
    | '/super/semesters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  SelectRoute: typeof SelectRoute
  SuperRoute: typeof SuperRouteWithChildren
  SubjectIdRoute: typeof SubjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/semesters': {
      id: '/super/semesters'
      path: '/semesters'
      fullPath: '/super/semesters'
      preLoaderRoute: typeof SuperSemestersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/activity': {
      id: '/super/activity'
      path: '/activity'
      fullPath: '/super/activity'
      preLoaderRoute: typeof SuperActivityRouteImport
      parentRoute: typeof SuperRoute
    }
    '/subject/$id': {
      id: '/subject/$id'
      path: '/subject/$id'
      fullPath: '/subject/$id'
      preLoaderRoute: typeof SubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperRouteChildren {
  SuperActivityRoute: typeof SuperActivityRoute
  SuperSemestersRoute: typeof SuperSemestersRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperActivityRoute: SuperActivityRoute,
  SuperSemestersRoute: SuperSemestersRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  SelectRoute: SelectRoute,
  SuperRoute: SuperRouteWithChildren,
  SubjectIdRoute: SubjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
