/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SelectRouteImport } from './routes/select'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperSubjectsRouteImport } from './routes/super.subjects'
import { Route as SuperSemestersRouteImport } from './routes/super.semesters'
import { Route as SuperRequestsRouteImport } from './routes/super.requests'
import { Route as SuperModulesRouteImport } from './routes/super.modules'
import { Route as SuperMaterialsRouteImport } from './routes/super.materials'
import { Route as SuperFeedbackRouteImport } from './routes/super.feedback'
import { Route as SuperDeadlinesRouteImport } from './routes/super.deadlines'
import { Route as SuperAnalyticsRouteImport } from './routes/super.analytics'
import { Route as SuperAiSettingsRouteImport } from './routes/super.ai-settings'
import { Route as SuperAdminsRouteImport } from './routes/super.admins'
import { Route as SuperActivityRouteImport } from './routes/super.activity'
import { Route as SubjectIdRouteImport } from './routes/subject.$id'
import { Route as SemesterIdRouteImport } from './routes/semester.$id'
import { Route as MaterialIdRouteImport } from './routes/material.$id'
import { Route as KuppiPresenterNameRouteImport } from './routes/kuppi-presenter.$name'
import { Route as ContributorsIdRouteImport } from './routes/contributors_.$id'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminMaterialsRouteImport } from './routes/admin.materials'
import { Route as AdminKuppiRouteImport } from './routes/admin.kuppi'
import { Route as AdminGuideRouteImport } from './routes/admin.guide'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminDeadlinesRouteImport } from './routes/admin.deadlines'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramNotifyMaterialsRouteImport } from './routes/api/public/telegram/notify-materials'
import { Route as ApiPublicTelegramHealthRouteImport } from './routes/api/public/telegram/health'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperSubjectsRoute = SuperSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSemestersRoute = SuperSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => SuperRoute,
} as any)
const SuperRequestsRoute = SuperRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => SuperRoute,
} as any)
const SuperModulesRoute = SuperModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => SuperRoute,
} as any)
const SuperMaterialsRoute = SuperMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => SuperRoute,
} as any)
const SuperFeedbackRoute = SuperFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDeadlinesRoute = SuperDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAnalyticsRoute = SuperAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAiSettingsRoute = SuperAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAdminsRoute = SuperAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperRoute,
} as any)
const SuperActivityRoute = SuperActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperRoute,
} as any)
const SubjectIdRoute = SubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterIdRoute = SemesterIdRouteImport.update({
  id: '/semester/$id',
  path: '/semester/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIdRoute = MaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KuppiPresenterNameRoute = KuppiPresenterNameRouteImport.update({
  id: '/kuppi-presenter/$name',
  path: '/kuppi-presenter/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsIdRoute = ContributorsIdRouteImport.update({
  id: '/contributors_/$id',
  path: '/contributors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKuppiRoute = AdminKuppiRouteImport.update({
  id: '/kuppi',
  path: '/kuppi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideRoute = AdminGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeadlinesRoute = AdminDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramNotifyMaterialsRoute =
  ApiPublicTelegramNotifyMaterialsRouteImport.update({
    id: '/api/public/telegram/notify-materials',
    path: '/api/public/telegram/notify-materials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramHealthRoute = ApiPublicTelegramHealthRouteImport.update({
  id: '/api/public/telegram/health',
  path: '/api/public/telegram/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contributors': typeof ContributorsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select': typeof SelectRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/deadlines': typeof AdminDeadlinesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/kuppi': typeof AdminKuppiRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/contributors/$id': typeof ContributorsIdRoute
  '/kuppi-presenter/$name': typeof KuppiPresenterNameRoute
  '/material/$id': typeof MaterialIdRoute
  '/semester/$id': typeof SemesterIdRoute
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/ai-settings': typeof SuperAiSettingsRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/deadlines': typeof SuperDeadlinesRoute
  '/super/feedback': typeof SuperFeedbackRoute
  '/super/materials': typeof SuperMaterialsRoute
  '/super/modules': typeof SuperModulesRoute
  '/super/requests': typeof SuperRequestsRoute
  '/super/semesters': typeof SuperSemestersRoute
  '/super/subjects': typeof SuperSubjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/notify-materials': typeof ApiPublicTelegramNotifyMaterialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contributors': typeof ContributorsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select': typeof SelectRoute
  '/admin/deadlines': typeof AdminDeadlinesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/kuppi': typeof AdminKuppiRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/contributors/$id': typeof ContributorsIdRoute
  '/kuppi-presenter/$name': typeof KuppiPresenterNameRoute
  '/material/$id': typeof MaterialIdRoute
  '/semester/$id': typeof SemesterIdRoute
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/ai-settings': typeof SuperAiSettingsRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/deadlines': typeof SuperDeadlinesRoute
  '/super/feedback': typeof SuperFeedbackRoute
  '/super/materials': typeof SuperMaterialsRoute
  '/super/modules': typeof SuperModulesRoute
  '/super/requests': typeof SuperRequestsRoute
  '/super/semesters': typeof SuperSemestersRoute
  '/super/subjects': typeof SuperSubjectsRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/notify-materials': typeof ApiPublicTelegramNotifyMaterialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contributors': typeof ContributorsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select': typeof SelectRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/deadlines': typeof AdminDeadlinesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/kuppi': typeof AdminKuppiRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/contributors_/$id': typeof ContributorsIdRoute
  '/kuppi-presenter/$name': typeof KuppiPresenterNameRoute
  '/material/$id': typeof MaterialIdRoute
  '/semester/$id': typeof SemesterIdRoute
  '/subject/$id': typeof SubjectIdRoute
  '/super/activity': typeof SuperActivityRoute
  '/super/admins': typeof SuperAdminsRoute
  '/super/ai-settings': typeof SuperAiSettingsRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/deadlines': typeof SuperDeadlinesRoute
  '/super/feedback': typeof SuperFeedbackRoute
  '/super/materials': typeof SuperMaterialsRoute
  '/super/modules': typeof SuperModulesRoute
  '/super/requests': typeof SuperRequestsRoute
  '/super/semesters': typeof SuperSemestersRoute
  '/super/subjects': typeof SuperSubjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/notify-materials': typeof ApiPublicTelegramNotifyMaterialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contributors'
    | '/dashboard'
    | '/help'
    | '/reset-password'
    | '/select'
    | '/super'
    | '/admin/deadlines'
    | '/admin/feedback'
    | '/admin/guide'
    | '/admin/kuppi'
    | '/admin/materials'
    | '/admin/modules'
    | '/admin/profile'
    | '/admin/requests'
    | '/contributors/$id'
    | '/kuppi-presenter/$name'
    | '/material/$id'
    | '/semester/$id'
    | '/subject/$id'
    | '/super/activity'
    | '/super/admins'
    | '/super/ai-settings'
    | '/super/analytics'
    | '/super/deadlines'
    | '/super/feedback'
    | '/super/materials'
    | '/super/modules'
    | '/super/requests'
    | '/super/semesters'
    | '/super/subjects'
    | '/admin/'
    | '/super/'
    | '/api/public/telegram/health'
    | '/api/public/telegram/notify-materials'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contributors'
    | '/dashboard'
    | '/help'
    | '/reset-password'
    | '/select'
    | '/admin/deadlines'
    | '/admin/feedback'
    | '/admin/guide'
    | '/admin/kuppi'
    | '/admin/materials'
    | '/admin/modules'
    | '/admin/profile'
    | '/admin/requests'
    | '/contributors/$id'
    | '/kuppi-presenter/$name'
    | '/material/$id'
    | '/semester/$id'
    | '/subject/$id'
    | '/super/activity'
    | '/super/admins'
    | '/super/ai-settings'
    | '/super/analytics'
    | '/super/deadlines'
    | '/super/feedback'
    | '/super/materials'
    | '/super/modules'
    | '/super/requests'
    | '/super/semesters'
    | '/super/subjects'
    | '/admin'
    | '/super'
    | '/api/public/telegram/health'
    | '/api/public/telegram/notify-materials'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contributors'
    | '/dashboard'
    | '/help'
    | '/reset-password'
    | '/select'
    | '/super'
    | '/admin/deadlines'
    | '/admin/feedback'
    | '/admin/guide'
    | '/admin/kuppi'
    | '/admin/materials'
    | '/admin/modules'
    | '/admin/profile'
    | '/admin/requests'
    | '/contributors_/$id'
    | '/kuppi-presenter/$name'
    | '/material/$id'
    | '/semester/$id'
    | '/subject/$id'
    | '/super/activity'
    | '/super/admins'
    | '/super/ai-settings'
    | '/super/analytics'
    | '/super/deadlines'
    | '/super/feedback'
    | '/super/materials'
    | '/super/modules'
    | '/super/requests'
    | '/super/semesters'
    | '/super/subjects'
    | '/admin/'
    | '/super/'
    | '/api/public/telegram/health'
    | '/api/public/telegram/notify-materials'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContributorsRoute: typeof ContributorsRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectRoute: typeof SelectRoute
  SuperRoute: typeof SuperRouteWithChildren
  ContributorsIdRoute: typeof ContributorsIdRoute
  KuppiPresenterNameRoute: typeof KuppiPresenterNameRoute
  MaterialIdRoute: typeof MaterialIdRoute
  SemesterIdRoute: typeof SemesterIdRoute
  SubjectIdRoute: typeof SubjectIdRoute
  ApiPublicTelegramHealthRoute: typeof ApiPublicTelegramHealthRoute
  ApiPublicTelegramNotifyMaterialsRoute: typeof ApiPublicTelegramNotifyMaterialsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super/subjects': {
      id: '/super/subjects'
      path: '/subjects'
      fullPath: '/super/subjects'
      preLoaderRoute: typeof SuperSubjectsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/semesters': {
      id: '/super/semesters'
      path: '/semesters'
      fullPath: '/super/semesters'
      preLoaderRoute: typeof SuperSemestersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/requests': {
      id: '/super/requests'
      path: '/requests'
      fullPath: '/super/requests'
      preLoaderRoute: typeof SuperRequestsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/modules': {
      id: '/super/modules'
      path: '/modules'
      fullPath: '/super/modules'
      preLoaderRoute: typeof SuperModulesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/materials': {
      id: '/super/materials'
      path: '/materials'
      fullPath: '/super/materials'
      preLoaderRoute: typeof SuperMaterialsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/feedback': {
      id: '/super/feedback'
      path: '/feedback'
      fullPath: '/super/feedback'
      preLoaderRoute: typeof SuperFeedbackRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/deadlines': {
      id: '/super/deadlines'
      path: '/deadlines'
      fullPath: '/super/deadlines'
      preLoaderRoute: typeof SuperDeadlinesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/analytics': {
      id: '/super/analytics'
      path: '/analytics'
      fullPath: '/super/analytics'
      preLoaderRoute: typeof SuperAnalyticsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/ai-settings': {
      id: '/super/ai-settings'
      path: '/ai-settings'
      fullPath: '/super/ai-settings'
      preLoaderRoute: typeof SuperAiSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/admins': {
      id: '/super/admins'
      path: '/admins'
      fullPath: '/super/admins'
      preLoaderRoute: typeof SuperAdminsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/activity': {
      id: '/super/activity'
      path: '/activity'
      fullPath: '/super/activity'
      preLoaderRoute: typeof SuperActivityRouteImport
      parentRoute: typeof SuperRoute
    }
    '/subject/$id': {
      id: '/subject/$id'
      path: '/subject/$id'
      fullPath: '/subject/$id'
      preLoaderRoute: typeof SubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$id': {
      id: '/semester/$id'
      path: '/semester/$id'
      fullPath: '/semester/$id'
      preLoaderRoute: typeof SemesterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$id': {
      id: '/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof MaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuppi-presenter/$name': {
      id: '/kuppi-presenter/$name'
      path: '/kuppi-presenter/$name'
      fullPath: '/kuppi-presenter/$name'
      preLoaderRoute: typeof KuppiPresenterNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors_/$id': {
      id: '/contributors_/$id'
      path: '/contributors/$id'
      fullPath: '/contributors/$id'
      preLoaderRoute: typeof ContributorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kuppi': {
      id: '/admin/kuppi'
      path: '/kuppi'
      fullPath: '/admin/kuppi'
      preLoaderRoute: typeof AdminKuppiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide': {
      id: '/admin/guide'
      path: '/guide'
      fullPath: '/admin/guide'
      preLoaderRoute: typeof AdminGuideRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deadlines': {
      id: '/admin/deadlines'
      path: '/deadlines'
      fullPath: '/admin/deadlines'
      preLoaderRoute: typeof AdminDeadlinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/notify-materials': {
      id: '/api/public/telegram/notify-materials'
      path: '/api/public/telegram/notify-materials'
      fullPath: '/api/public/telegram/notify-materials'
      preLoaderRoute: typeof ApiPublicTelegramNotifyMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/health': {
      id: '/api/public/telegram/health'
      path: '/api/public/telegram/health'
      fullPath: '/api/public/telegram/health'
      preLoaderRoute: typeof ApiPublicTelegramHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDeadlinesRoute: typeof AdminDeadlinesRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminGuideRoute: typeof AdminGuideRoute
  AdminKuppiRoute: typeof AdminKuppiRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDeadlinesRoute: AdminDeadlinesRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminGuideRoute: AdminGuideRoute,
  AdminKuppiRoute: AdminKuppiRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperActivityRoute: typeof SuperActivityRoute
  SuperAdminsRoute: typeof SuperAdminsRoute
  SuperAiSettingsRoute: typeof SuperAiSettingsRoute
  SuperAnalyticsRoute: typeof SuperAnalyticsRoute
  SuperDeadlinesRoute: typeof SuperDeadlinesRoute
  SuperFeedbackRoute: typeof SuperFeedbackRoute
  SuperMaterialsRoute: typeof SuperMaterialsRoute
  SuperModulesRoute: typeof SuperModulesRoute
  SuperRequestsRoute: typeof SuperRequestsRoute
  SuperSemestersRoute: typeof SuperSemestersRoute
  SuperSubjectsRoute: typeof SuperSubjectsRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperActivityRoute: SuperActivityRoute,
  SuperAdminsRoute: SuperAdminsRoute,
  SuperAiSettingsRoute: SuperAiSettingsRoute,
  SuperAnalyticsRoute: SuperAnalyticsRoute,
  SuperDeadlinesRoute: SuperDeadlinesRoute,
  SuperFeedbackRoute: SuperFeedbackRoute,
  SuperMaterialsRoute: SuperMaterialsRoute,
  SuperModulesRoute: SuperModulesRoute,
  SuperRequestsRoute: SuperRequestsRoute,
  SuperSemestersRoute: SuperSemestersRoute,
  SuperSubjectsRoute: SuperSubjectsRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContributorsRoute: ContributorsRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectRoute: SelectRoute,
  SuperRoute: SuperRouteWithChildren,
  ContributorsIdRoute: ContributorsIdRoute,
  KuppiPresenterNameRoute: KuppiPresenterNameRoute,
  MaterialIdRoute: MaterialIdRoute,
  SemesterIdRoute: SemesterIdRoute,
  SubjectIdRoute: SubjectIdRoute,
  ApiPublicTelegramHealthRoute: ApiPublicTelegramHealthRoute,
  ApiPublicTelegramNotifyMaterialsRoute: ApiPublicTelegramNotifyMaterialsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
